/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppEmailsRouteImport } from './routes/app.emails'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppDealsIndexRouteImport } from './routes/app.deals.index'
import { Route as AppContactsIndexRouteImport } from './routes/app.contacts.index'
import { Route as AppCompaniesIndexRouteImport } from './routes/app.companies.index'
import { Route as AppSettingsCustomFieldsRouteImport } from './routes/app.settings.custom-fields'
import { Route as AppDealsIdRouteImport } from './routes/app.deals.$id'
import { Route as AppContactsIdRouteImport } from './routes/app.contacts.$id'
import { Route as AppCompaniesIdRouteImport } from './routes/app.companies.$id'
import { Route as AppActivitiesIdRouteImport } from './routes/app.activities.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailsRoute = AppEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCustomFieldsRoute = AppSettingsCustomFieldsRouteImport.update({
  id: '/custom-fields',
  path: '/custom-fields',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppDealsIdRoute = AppDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesIdRoute = AppCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesIdRoute = AppActivitiesIdRouteImport.update({
  id: '/activities/$id',
  path: '/activities/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/emails': typeof AppEmailsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/tasks': typeof AppTasksRoute
  '/app/': typeof AppIndexRoute
  '/app/activities/$id': typeof AppActivitiesIdRoute
  '/app/companies/$id': typeof AppCompaniesIdRoute
  '/app/contacts/$id': typeof AppContactsIdRoute
  '/app/deals/$id': typeof AppDealsIdRoute
  '/app/settings/custom-fields': typeof AppSettingsCustomFieldsRoute
  '/app/companies/': typeof AppCompaniesIndexRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/deals/': typeof AppDealsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/emails': typeof AppEmailsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app': typeof AppIndexRoute
  '/app/activities/$id': typeof AppActivitiesIdRoute
  '/app/companies/$id': typeof AppCompaniesIdRoute
  '/app/contacts/$id': typeof AppContactsIdRoute
  '/app/deals/$id': typeof AppDealsIdRoute
  '/app/settings/custom-fields': typeof AppSettingsCustomFieldsRoute
  '/app/companies': typeof AppCompaniesIndexRoute
  '/app/contacts': typeof AppContactsIndexRoute
  '/app/deals': typeof AppDealsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/emails': typeof AppEmailsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/tasks': typeof AppTasksRoute
  '/app/': typeof AppIndexRoute
  '/app/activities/$id': typeof AppActivitiesIdRoute
  '/app/companies/$id': typeof AppCompaniesIdRoute
  '/app/contacts/$id': typeof AppContactsIdRoute
  '/app/deals/$id': typeof AppDealsIdRoute
  '/app/settings/custom-fields': typeof AppSettingsCustomFieldsRoute
  '/app/companies/': typeof AppCompaniesIndexRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/deals/': typeof AppDealsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/dashboard'
    | '/app/emails'
    | '/app/settings'
    | '/app/tasks'
    | '/app/'
    | '/app/activities/$id'
    | '/app/companies/$id'
    | '/app/contacts/$id'
    | '/app/deals/$id'
    | '/app/settings/custom-fields'
    | '/app/companies/'
    | '/app/contacts/'
    | '/app/deals/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/dashboard'
    | '/app/emails'
    | '/app/tasks'
    | '/app'
    | '/app/activities/$id'
    | '/app/companies/$id'
    | '/app/contacts/$id'
    | '/app/deals/$id'
    | '/app/settings/custom-fields'
    | '/app/companies'
    | '/app/contacts'
    | '/app/deals'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/dashboard'
    | '/app/emails'
    | '/app/settings'
    | '/app/tasks'
    | '/app/'
    | '/app/activities/$id'
    | '/app/companies/$id'
    | '/app/contacts/$id'
    | '/app/deals/$id'
    | '/app/settings/custom-fields'
    | '/app/companies/'
    | '/app/contacts/'
    | '/app/deals/'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emails': {
      id: '/app/emails'
      path: '/emails'
      fullPath: '/app/emails'
      preLoaderRoute: typeof AppEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/deals/': {
      id: '/app/deals/'
      path: '/deals'
      fullPath: '/app/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts/': {
      id: '/app/contacts/'
      path: '/contacts'
      fullPath: '/app/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/': {
      id: '/app/companies/'
      path: '/companies'
      fullPath: '/app/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/custom-fields': {
      id: '/app/settings/custom-fields'
      path: '/custom-fields'
      fullPath: '/app/settings/custom-fields'
      preLoaderRoute: typeof AppSettingsCustomFieldsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/deals/$id': {
      id: '/app/deals/$id'
      path: '/deals/$id'
      fullPath: '/app/deals/$id'
      preLoaderRoute: typeof AppDealsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts/$id': {
      id: '/app/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/app/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies/$id': {
      id: '/app/companies/$id'
      path: '/companies/$id'
      fullPath: '/app/companies/$id'
      preLoaderRoute: typeof AppCompaniesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activities/$id': {
      id: '/app/activities/$id'
      path: '/activities/$id'
      fullPath: '/app/activities/$id'
      preLoaderRoute: typeof AppActivitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsCustomFieldsRoute: typeof AppSettingsCustomFieldsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsCustomFieldsRoute: AppSettingsCustomFieldsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmailsRoute: typeof AppEmailsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppActivitiesIdRoute: typeof AppActivitiesIdRoute
  AppCompaniesIdRoute: typeof AppCompaniesIdRoute
  AppContactsIdRoute: typeof AppContactsIdRoute
  AppDealsIdRoute: typeof AppDealsIdRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEmailsRoute: AppEmailsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppActivitiesIdRoute: AppActivitiesIdRoute,
  AppCompaniesIdRoute: AppCompaniesIdRoute,
  AppContactsIdRoute: AppContactsIdRoute,
  AppDealsIdRoute: AppDealsIdRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
